/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brown;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author csstudent
 */
public class coke extends javax.swing.JFrame {

    String drink1 = "Your drink is: Sprite";
    String drink2 = "Your drink is: Coca-Cola";
    String drink3 = "Your drink is: Cherry Coke";
    String drink4 = "Your drink is: Pineapple Fanta";
    String drink5 = "Your drink is: Grape Fanta";
    String drink6 = "Your drink is: Strawberry Fanta";
    String drink7 = "Your drink is: Fruit Punch Hi-C";
    String drink8 = "Your drink is: Sweet Tea";
    String drink9 = "Your drink is: Water";
    String drink10 = "Your drink is: Lemonade";

    Connection con = new DBConnection().connect();

    /**
     * Creates new form coke
     */
    public coke() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pine = new javax.swing.JRadioButton();
        cherry = new javax.swing.JRadioButton();
        coca = new javax.swing.JRadioButton();
        straw = new javax.swing.JRadioButton();
        sprite = new javax.swing.JRadioButton();
        grape = new javax.swing.JRadioButton();
        hi = new javax.swing.JRadioButton();
        lemon = new javax.swing.JRadioButton();
        tea = new javax.swing.JRadioButton();
        wat = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Drinks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(153, 153, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));

        pine.setBackground(new java.awt.Color(51, 51, 51));
        pine.setForeground(new java.awt.Color(153, 153, 255));
        pine.setText("Fanta Pineapple");
        pine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pineActionPerformed(evt);
            }
        });

        cherry.setBackground(new java.awt.Color(51, 51, 51));
        cherry.setForeground(new java.awt.Color(153, 153, 255));
        cherry.setText("Cherry Coke");
        cherry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cherryActionPerformed(evt);
            }
        });

        coca.setBackground(new java.awt.Color(51, 51, 51));
        coca.setForeground(new java.awt.Color(153, 153, 255));
        coca.setText("Coca-Cola");
        coca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocaActionPerformed(evt);
            }
        });

        straw.setBackground(new java.awt.Color(51, 51, 51));
        straw.setForeground(new java.awt.Color(153, 153, 255));
        straw.setText("Fanta Strawberry");
        straw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawActionPerformed(evt);
            }
        });

        sprite.setBackground(new java.awt.Color(51, 51, 51));
        sprite.setForeground(new java.awt.Color(153, 153, 255));
        sprite.setText("Sprite");
        sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteActionPerformed(evt);
            }
        });

        grape.setBackground(new java.awt.Color(51, 51, 51));
        grape.setForeground(new java.awt.Color(153, 153, 255));
        grape.setText("Fanta Grape");
        grape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grapeActionPerformed(evt);
            }
        });

        hi.setBackground(new java.awt.Color(51, 51, 51));
        hi.setForeground(new java.awt.Color(153, 153, 255));
        hi.setText("Fruit Punch Hi-C");

        lemon.setBackground(new java.awt.Color(51, 51, 51));
        lemon.setForeground(new java.awt.Color(153, 153, 255));
        lemon.setText("Lemonade");
        lemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemonActionPerformed(evt);
            }
        });

        tea.setBackground(new java.awt.Color(51, 51, 51));
        tea.setForeground(new java.awt.Color(153, 153, 255));
        tea.setText("Sweet Tea");

        wat.setBackground(new java.awt.Color(51, 51, 51));
        wat.setForeground(new java.awt.Color(153, 153, 255));
        wat.setText("Water");
        wat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cherry)
                    .addComponent(coca)
                    .addComponent(hi)
                    .addComponent(tea)
                    .addComponent(sprite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(straw)
                    .addComponent(grape)
                    .addComponent(wat)
                    .addComponent(pine)
                    .addComponent(lemon))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sprite)
                    .addComponent(pine))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hi)
                    .addComponent(lemon))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coca)
                    .addComponent(grape))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tea)
                    .addComponent(wat))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(straw)
                    .addComponent(cherry))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(153, 153, 255));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(153, 153, 255));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(85, 85, 85)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteActionPerformed
        coke = "Sprite"; // TODO add your handling code here:
    }//GEN-LAST:event_spriteActionPerformed

    private void cocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocaActionPerformed
        coke = "Coca-Cola";        // TODO add your handling code here:
    }//GEN-LAST:event_cocaActionPerformed

    private void cherryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cherryActionPerformed
        coke = "Chery Coke";        // TODO add your handling code here:
    }//GEN-LAST:event_cherryActionPerformed

    private void pineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pineActionPerformed
        coke = "Pineapple Fanta";        // TODO add your handling code here:
    }//GEN-LAST:event_pineActionPerformed

    private void grapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grapeActionPerformed
        coke = "Grape Fanta";        // TODO add your handling code here:
    }//GEN-LAST:event_grapeActionPerformed

    private void strawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawActionPerformed
        coke = "Strawberry Fanta";        // TODO add your handling code here:
    }//GEN-LAST:event_strawActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*String sql = "insert into login Bill(?)";
         Connection con = null;
         PreparedStatement ps = null;

         try {
         ps = con.prepareStatement(sql);
         ps.setString(1, coke);
         ps.executeUpdate();

         } catch (Exception e) {

         }*/         // TODO add your handling code here:
        if (sprite.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n" + drink1);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (coca.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n" + drink2);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (cherry.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n" + drink3);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (pine.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n" + drink4);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (grape.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n" + drink5);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (straw.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n" + drink6);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (hi.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n" + drink7);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (wat.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n" + drink9);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (lemon.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n" + drink10);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (tea.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n" + drink8);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        close();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        welcome W = new welcome();
        W.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void watActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watActionPerformed

    private void lemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lemonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coke().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cherry;
    private javax.swing.JRadioButton coca;
    private javax.swing.JRadioButton grape;
    private javax.swing.JRadioButton hi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton lemon;
    private javax.swing.JRadioButton pine;
    private javax.swing.JRadioButton sprite;
    private javax.swing.JRadioButton straw;
    private javax.swing.JRadioButton tea;
    private javax.swing.JRadioButton wat;
    // End of variables declaration//GEN-END:variables
private String coke;

    private void close() {
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}
