/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brown;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author De'Angelo
 */
public class dessert extends javax.swing.JFrame {

    String po = "$1.59";
    String velvet = "$2.00";
    String pie = "$1.25";
    String pudding = "$1.59";
    String bpie = "$1.79";
    String cheese = "$2.00";

    /**
     * Creates new form dessert
     */
    public dessert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pound = new javax.swing.JCheckBox();
        boston = new javax.swing.JCheckBox();
        ny = new javax.swing.JCheckBox();
        banana = new javax.swing.JCheckBox();
        apple = new javax.swing.JCheckBox();
        red = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deserts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(153, 153, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));

        pound.setBackground(new java.awt.Color(51, 51, 51));
        pound.setForeground(new java.awt.Color(153, 153, 255));
        pound.setText("Pound Cake");
        pound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poundActionPerformed(evt);
            }
        });

        boston.setBackground(new java.awt.Color(51, 51, 51));
        boston.setForeground(new java.awt.Color(153, 153, 255));
        boston.setText("Boston Creme Pie");

        ny.setBackground(new java.awt.Color(51, 51, 51));
        ny.setForeground(new java.awt.Color(153, 153, 255));
        ny.setText("NY Style Cheesecake");

        banana.setBackground(new java.awt.Color(51, 51, 51));
        banana.setForeground(new java.awt.Color(153, 153, 255));
        banana.setText("Banana Pudding");

        apple.setBackground(new java.awt.Color(51, 51, 51));
        apple.setForeground(new java.awt.Color(153, 153, 255));
        apple.setText("Apple Pie");

        red.setBackground(new java.awt.Color(51, 51, 51));
        red.setForeground(new java.awt.Color(153, 153, 255));
        red.setText("Red Velvet Cake");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(red)
                .addGap(52, 52, 52)
                .addComponent(apple)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(banana)
                .addGap(48, 48, 48)
                .addComponent(boston)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ny)
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pound)
                    .addComponent(red)
                    .addComponent(apple))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banana)
                    .addComponent(boston))
                .addGap(27, 27, 27)
                .addComponent(ny)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(153, 153, 255));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(153, 153, 255));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(90, 90, 90)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        close();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void poundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poundActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (pound.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n There has been an addition to your balance: Pound Cake =" + po);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (red.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n There has been an addition to your balance: Red Velvet Cake =" + velvet);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (apple.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n There has been an addition to your balance: Apple Pie =" + pie);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (banana.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n There has been an addition to your balance: Banana Pudding =" + pudding);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (boston.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n There has been an addition to your balance: Boston Creme Pie =" + bpie);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
        if (ny.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n There has been an addition to your balance: NY Style Cheesecake =" + cheese);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        welcome W = new welcome();
        W.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dessert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dessert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dessert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dessert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dessert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox apple;
    private javax.swing.JCheckBox banana;
    private javax.swing.JCheckBox boston;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox ny;
    private javax.swing.JCheckBox pound;
    private javax.swing.JCheckBox red;
    // End of variables declaration//GEN-END:variables
private void close() {
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}
