/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brown;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author csstudent
 */
public class entrees extends javax.swing.JFrame {

    String pork1 = "$4.59";
    String turkey1 = "$4.00";
    String bbq1 = "$5.25";
    String chops1 = "$4.59";
    String fried1 = "$5.79";

    /**
     * Creates new form entrees
     */
    public entrees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        turkey = new javax.swing.JCheckBox();
        pork = new javax.swing.JCheckBox();
        fried = new javax.swing.JCheckBox();
        chops = new javax.swing.JCheckBox();
        bbq = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Dishes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(153, 153, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));

        turkey.setBackground(new java.awt.Color(51, 51, 51));
        turkey.setForeground(new java.awt.Color(153, 153, 255));
        turkey.setText("Turkey Wings");

        pork.setBackground(new java.awt.Color(51, 51, 51));
        pork.setForeground(new java.awt.Color(153, 153, 255));
        pork.setText("Pulled Pork");
        pork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porkActionPerformed(evt);
            }
        });

        fried.setBackground(new java.awt.Color(51, 51, 51));
        fried.setForeground(new java.awt.Color(153, 153, 255));
        fried.setText("Fried Chicken");
        fried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friedActionPerformed(evt);
            }
        });

        chops.setBackground(new java.awt.Color(51, 51, 51));
        chops.setForeground(new java.awt.Color(153, 153, 255));
        chops.setText("Fried Pork Chop");

        bbq.setBackground(new java.awt.Color(51, 51, 51));
        bbq.setForeground(new java.awt.Color(153, 153, 255));
        bbq.setText("Barbequed Chicken");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(turkey)
                    .addComponent(fried))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bbq)
                    .addComponent(chops))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(pork)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fried)
                    .addComponent(chops))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turkey)
                    .addComponent(bbq))
                .addGap(36, 36, 36)
                .addComponent(pork)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(153, 153, 255));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(153, 153, 255));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(96, 96, 96)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void porkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        welcome W = new welcome();
        W.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (pork.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n There has been an addition to your balance: Pulled Pork = " + pork1);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }

        if (turkey.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n There has been an addition to your balance: Turkey = " + turkey1);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }

        if (bbq.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n There has been an addition to your balance: Barbequed Chicken = " + bbq1);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }

        if (fried.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n There has been an addition to your balance: Fried Chicken = " + fried1);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }

        if (chops.isSelected()) {
            try {
                String filename = "order.txt";
                try (FileWriter fw = new FileWriter(filename, true) //the true will append the new data
                        ) {
                    fw.write("\r\n There has been an addition to your balance: Pork Chops = " + chops1);//appends the string to the file
                } //appends the string to the file
            } catch (IOException ioe) {
                System.err.println("Baddd" + ioe.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        close();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void friedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entrees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entrees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entrees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entrees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entrees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bbq;
    private javax.swing.JCheckBox chops;
    private javax.swing.JCheckBox fried;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox pork;
    private javax.swing.JCheckBox turkey;
    // End of variables declaration//GEN-END:variables
private void close() {
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }

}
